- legend-sdlc-server-shared/pom.xml
- legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/monitoring/SDLCMetricsHandler.java
- legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/resources/BaseResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceEntitiesResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspacesResource.java
- pom.xml
Enables SDLC endpoints dynamic metrics for monitoring.
> Enable dynamic metrics

- README.md
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java
Improvements to the instructions in README.md on starting the SDLC Server, a bug fix related to project structure configuration, and two regex bug fixes
> README improvements and bug fixes

- legend-sdlc-server/pom.xml
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/AbstractGitLabApiTest.java
- pom.xml
Allow skipping integration tests and selecting test GitLab image version. #96
> Allow skipping integration tests and selecting test GitLab image version.

- README.md
- legend-sdlc-server/src/test/resources/config-sample.yaml
See https://github.com/finos/legend/pull/376
> Update sample config file to match installation guide

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabConflictResolutionApi.java
Add waits to allow nodes communications during conflict resolution.
> Add waits to allow nodes communications during conflict resolution

- .github/workflows/gitlab-com-integration-test.yml
Toggle daily gitlab.com tests.
> Toggle daily gitlab.com tests

- .github/workflows/gitlab-com-integration-test.yml
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerEntityApis.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerProjectApis.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerWorkspaceApis.java
Add null check on teardowns and skip int test on forks.
> Add null check on teardowns and skip int test on forks

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabBuildApi.java
> Use weburl from pipeline instead of constructing the URL manually

- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
Fix flaky entity test assertion error.
> Fix flaky entity test assertion error

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/workflow/Workflow.java
- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/workflow/WorkflowStatus.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/workflow/WorkflowAccessContext.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/workflow/WorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/BaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectBuildsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectWorkflowsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionBuildsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionWorkflowsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceBuildsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceWorkflowsResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/guice/InMemoryModule.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryWorkflowApi.java
* Add new Workflow model and related Gitlab APIs
* Mark Build APIs as deprecated
> Add new workflow API

- .github/workflows/gitlab-com-integration-test.yml
- .github/workflows/gitlab-docker-int-test-latest-twelve.yml
- .github/workflows/gitlab-docker-int-test-latest.yml
- .github/workflows/gitlab-docker-int-test-nightly.yml
- .github/workflows/gitlab-docker-integration-test.yml
- legend-sdlc-server/pom.xml
- pom.xml
Move container management into workflows.
> Move container management into workflows

- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
Correct post-merge worksapce check logic, add call until.
> Entity test improvement

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/tools/PagerTools.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiTestSetupUtil.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabWorkspaceApis.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerWorkspaceApis.java
Fix pager issue blocking workspace update.
> Fix pager issue blocking workspace update

- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/AbstractGitLabApiTest.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/AbstractGitLabServerApiTest.java
Fix test thread issue by applying correct backgroundTaskProcessor instantiation.
> Fix test thread issue.

- .github/workflows/gitlab-com-integration-test.yml
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/AbstractGitLabServerApiTest.java
Add tag for integration test projects.
> Add tag for integration test projects

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java
Mute test branch deletion exception throwing.
> Mute test branch deletion exception throwing

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectConfigurationApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabRevisionApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectPaths.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/InMemoryProjectFileAccessProvider.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructure.java
Fix canonical directory and file paths
> Fix canonical directory and file paths

- legend-sdlc-generation-file-maven-plugin/pom.xml
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/entities/model/MyGenerationSpecification.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/entities/model/myJSONSchema.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/entities/model/myYAMLSchema.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/complex/AddressWithConstraint.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/Address.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/City.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/Country.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/Firm.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/IncType.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myJSONSchema/model/Person.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/Address.yaml
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/City.yaml
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/Country.yaml
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/Firm.yaml
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/IncType.yaml
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model_myYAMLSchema/model/Person.yaml
- legend-sdlc-generation-file/pom.xml
- legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/file/GenerationOutput.java
- pom.xml
Fix escaping for yaml generation
> add tests for yaml and json schema generation.

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/review/ReviewApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsOnlyResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryReviewApi.java
Get all reviews with the given state
> Get reviews without specifying project id

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
Fix the logic change issue that affects WorkspaceType-related branch name generation.
> Fix branch name creation logic.

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/test/TestModelBuilder.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/utils/TestModelBuilderTest.java
Build entities for test with version id for upstream project
> Build entities for test with version id for upstream project

- legend-sdlc-entity-maven-plugin/pom.xml
- legend-sdlc-entity-serialization/pom.xml
- legend-sdlc-extensions-collection-entity-serializer/pom.xml
- legend-sdlc-generation-file-maven-plugin/pom.xml
- legend-sdlc-generation-file/pom.xml
- legend-sdlc-generation-model-maven-plugin/pom.xml
- legend-sdlc-generation-model/pom.xml
- legend-sdlc-generation-service-maven-plugin/pom.xml
- legend-sdlc-generation-service/pom.xml
- legend-sdlc-language-pure-compiler/pom.xml
- legend-sdlc-model/pom.xml
- legend-sdlc-protocol-pure/pom.xml
- legend-sdlc-protocol/pom.xml
- legend-sdlc-server-shared/pom.xml
- legend-sdlc-server/pom.xml
- legend-sdlc-test-utils/pom.xml
- legend-sdlc-version-package-maven-plugin/pom.xml
- pom.xml
- test-reports/pom.xml
Prepare for next development iteration
> Prepare for next development iteration

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/BaseModule.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/resources/LegendSDLCServerForIntegrationTest.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/resources/TestLegendSDLCServerAccessibility.java
Bind MetadataApi to DepotMetadataApi
> Bind MetadataApi to DepotMetadataApi

- legend-sdlc-server/pom.xml
@kevin-m-knight-gs  I have tested this. This should work if secrets are set properly. My test repo is at
https://github.com/akphi/legend-test-space/runs/4439338167?check_suite_focus=true
> fix Docker snapshot build CI

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/accessRole/ProjectAuthorizationAction.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectsResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectApi.java
> User authorization check

- pom.xml
- test-reports/pom.xml
Adding the nexus staging maven plugin to allow for easy deployments to Maven Central
> Adding nexus staging plugin

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureV12Factory.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendServiceExecutionGenerationPluginMavenHelper.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendTestUtilsMavenHelper.java
- legend-sdlc-server/src/main/resources/META-INF/services/org.finos.legend.sdlc.server.project.ProjectStructureVersionFactory
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestMultiGenerationProjectStructure.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureFactory.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureStaticMethods.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureV12.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/extension/TestDefaultProjectStructureExtensionProvider.java
- Enable fat service execution jar generation 
- Enable Java 11 with useSystemClassLoader
> Create new project structure v12.

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOAuthAuthenticator.java
Newer versions (v13.12.15-ee at the time of writing) have modified the OAuth authorization behaviour. The /authorize call returns 200 for both successful authZ and pending authZ. This change allows the capture of redirect URL even on the 200 response.
> Update OAuth flow to accommodate new GitLab behaviour

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/Project.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/domain/api/InMemoryProject.java
Add `webUrl` attribute to `Project` model - see https://github.com/finos/legend-studio/issues/905 for more context
> add webUrl for project

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/workflow/WorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/workflow/WorkflowJobApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowJobApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceWorkflowJobsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewWorkflowJobsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewWorkflowsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionWorkflowJobsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionWorkflowsResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceWorkflowJobsResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryWorkflowApi.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryWorkflowJobApi.java
Add APIs to get workflows and workflow jobs for reviews. In passing, fix some typos in workflow resources.
> Add review workflow APIs

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendServiceExecutionGenerationPluginMavenHelper.java
- Fix project structure v12 service-exec pom to be not dependency reduced.
> Fix project structure v12 service-exec pom to be not dependency reduced.

- legend-sdlc-test-utils/pom.xml
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/ServiceTestCase.java
Uplift test strategy phase 1
Depends on - https://github.com/finos/legend-engine/pull/631
> Uplift test strategy phase 1

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/finos/FinosGitlabProjectStructureExtensionProvider.java
- legend-sdlc-server/src/main/resources/org/finos/legend/sdlc/server/gitlab/finos/gitlab-ci-2.yml
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/finos/TestFinosGitlabProjectStructureExtension.java
Fix project structure extension version for finos.
Add -Xmx8g in gitlab ci file to prevent out of heap error during build
> Fix extension provider for finos

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/AbstractGitlabWorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowJobApi.java
Fix bugs in getting workflows and jobs for reviews. The API was not returning all workflows for reviews. Now all are returned.
> Fix bugs in getting workflows and jobs for reviews

- legend-sdlc-server/pom.xml
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureFactory.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectFileConfiguration.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/extension/DefaultProjectStructureExtension.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/extension/SimpleProjectStructureExtensionProvider.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/MavenProjectStructure.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/tools/IOTools.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/extension/TestDefaultProjectStructureExtensionProvider.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/extension/TestSimpleProjectStructureExtensionProvider.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/tools/TestIOTools.java
Improvements to project structure extensions, especially in provider configuration options.
> Project structure extension improvements

- legend-sdlc-test-utils/pom.xml
- pom.xml
- test-reports/pom.xml
Update Legend versions. Also, clean up a few poms.
> Update Legend versions

- legend-sdlc-test-utils/pom.xml
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/TestableTestCase.java
- legend-sdlc-test-utils/src/test/java/org/finos/legend/sdlc/test/junit/TestLegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-m2m-mapping-model-with-tests/entities/model/mapping/SourceToTargetM2M.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/Employee.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/Employee2.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/ServiceStore.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/ServiceStoreConnection.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/ServiceStoreMapping.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/ServiceStoreRuntime.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/TestData.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/TestService.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/TestService2.json
- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/employeeServiceStoreSchemaBinding.json
- pom.xml
Depends on : https://github.com/finos/legend-engine/pull/652
> Run testable tests in SDLC pipeline

- .github/workflows/build.yml
- legend-sdlc-test-reports/pom.xml
- pom.xml
- test-reports/pom.xml
Rename test-reports-to legend-sdlc-test-reports
> Rename test-reports-to legend-sdlc-test-reports

- .github/workflows/build.yml
Ensure "Build + Test + Maven Deploy + Sonar + Docker Snapshot" fails if there are test failures.
> Ensure "Build + Test + Maven Deploy + Sonar + Docker Snapshot" fails if there are test failures

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java
> Fix possible null pointer bug

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectPlatformsConfiguration.java
Improve error handling in platform version configuration.
> Improve error handling in platform version configuration

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
Improve error messages when committing a review. We now propagate the underlying error message in case of 401/403 status, and also include a link to the MR.
> Improve error messages when committing a review

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/entity/EntityApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabConflictResolutionApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryEntityApi.java
Gitlab Conflict resolution API could not resolve the right group workspace when accepting resolution.
> Fix a problem with conflict resolution for group workspaces

- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java
- legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/tools/StringTools.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/config/LegendSDLCServerFeaturesConfiguration.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectConfigurationApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/resources/GitLabAuthResource.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectPaths.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectCreationConfiguration.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/MavenProjectStructure.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspacesResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabProjectConfigurationApis.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerProjectConfigurationApis.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestCase.java
- legend-sdlc-version-package-maven-plugin/src/main/java/org/finos/legend/sdlc/versions/VersionQualifiedPackageMojo.java
Code clean up. This includes removing some unused imports, unused parameters, and unused private methods, as well as other similar sorts of clean ups.
> Clean up some code

- pom.xml
Update legend-engine dependency
> Update legend-engine version

- legend-sdlc-entity-serialization/pom.xml
- legend-sdlc-entity-serialization/src/main/java/org/finos/legend/sdlc/serialization/EntityLoader.java
- legend-sdlc-entity-serialization/src/main/java/org/finos/legend/sdlc/serialization/EntitySerializers.java
- legend-sdlc-entity-serialization/src/test/java/org/finos/legend/sdlc/serialization/TestClassLoaderEntityLoader.java
- legend-sdlc-entity-serialization/src/test/java/org/finos/legend/sdlc/serialization/TestEntityLoader.java
- legend-sdlc-entity-serialization/src/test/java/org/finos/legend/sdlc/serialization/TestEntitySerializers.java
- legend-sdlc-entity-serialization/src/test/java/org/finos/legend/sdlc/serialization/TestJarDirectoriesEntityLoader.java
Reduce dependencies in legend-sdlc-entity-serialization
> Reduce dependencies in legend-sdlc-entity-serialization

- legend-sdlc-entity-maven-plugin/src/main/java/org/finos/legend/sdlc/entities/EntityReserializer.java
- legend-sdlc-entity-serialization/src/main/java/org/finos/legend/sdlc/serialization/EntitySerializer.java
- legend-sdlc-entity-serialization/src/main/java/org/finos/legend/sdlc/serialization/EntityTextSerializer.java
- legend-sdlc-entity-serialization/src/test/java/org/finos/legend/sdlc/serialization/TestEntitySerializer.java
- legend-sdlc-generation-model-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/model/ModelGenerationMojo.java
- legend-sdlc-version-package-maven-plugin/src/main/java/org/finos/legend/sdlc/versions/VersionQualifiedPackageMojo.java
Add methods to EntitySerializer for serializing to files. Also add methods for generating file paths for entities.
> Add methods to EntitySerializer for serializing to files

- .github/workflows/docker.yml
Only run the Docker workflow on pushes and pull requests if Dockerfile is modified
> Only run the Docker workflow on pushes and PRs if Dockerfile is modified

- pom.xml
Upgrade to legend-engine 3.14.5
> Upgrade to legend-engine 3.14.5

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java
Fix bugs in logging and error messages that assume a workspace is always present
> Fix bugs in logging/error messages that assume a workspace is always present

- pom.xml
Uptick legend engine version to 3.15.2
> Uptick legend engine version to 3.15.2

- pom.xml
> Update pure, engine versions

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabBuildApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabComparisonApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabConflictResolutionApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabRevisionApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabVersionApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowJobApi.java
Checking default protected branch for any operations
> Checking default protected branch for any operations

- legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/artifact/ArtifactGenerationFactory.java
- legend-sdlc-generation-file/src/test/java/org/finos/legend/sdlc/generation/artifact/TestArtifactGenerationFactory.java
- legend-sdlc-generation-file/src/test/java/org/finos/legend/sdlc/generation/artifact/TestSimpleEnumArtifactGenerationExtension.java
- legend-sdlc-generation-file/src/test/java/org/finos/legend/sdlc/generation/artifact/TestSimpleFunctionArtifactGenerationExtension.java
- legend-sdlc-generation-file/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationFactory.java
- legend-sdlc-generation-file/src/test/resources/ArtifactGenerationFactoryTestData.json
- legend-sdlc-generation-file/src/test/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension
- safely find packagable element in pure model
- special casing for functions using function signature
- continue on to next element if unable to find it in pureModel
> safely find packageable element in pure model for artifact generation

- .github/workflows/build.yml
same reasoning as in https://github.com/finos/legend-engine/pull/1023
> unignore test failure in PR CIs

- pom.xml
> Update engine version

- pom.xml
update legend engine version to 3.19.4
> update legend engine version to 3.19.4

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/review/Approval.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/review/ReviewApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryReviewApi.java
Add /reviews/{reviewId}/approval API
> Add /reviews/{reviewId}/approval API

- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
- pom.xml
support function overloading (minor test fix)
> support function overloading (minor test fix)

- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
support function overloading minor fix
> support function overloading minor fix

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/tools/entity/EntityPaths.java
- legend-sdlc-model/src/test/java/org/finos/legend/sdlc/tools/entity/TestEntityPaths.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabRevisionApi.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/EntityValidator.java
Move entity path validation to legend-sdlc-model.
> Move entity path validation to legend-sdlc-model

- pom.xml
update legend-engine to 3.23.2 and legend-pure to 3.7.3
> update legend-engine to 3.23.2 and legend-pure to 3.7.3

- pom.xml
Upgrade to Pure 3.8.0 and Engine 3.25.0
> Upgrade to Pure 3.8.0 and Engine 3.25.0

- pom.xml
Update legend-engine to 3.28.0
> Update legend-engine to 3.28.0

- pom.xml
update legend-engine to 3.29.0 and legend-pure to 3.8.1
> update legend-engine/legend-pure dependencies

- pom.xml
Update legend-engine to 3.30.1
> Update legend-engine to 3.30.1

- pom.xml
Upgrade Engine to 3.31.0, Pure to 3.8.2
> Upgrade Engine to 3.31.0, Pure to 3.8.2

- pom.xml
Upgrade legend-engine to 3.35.1
> Upgrade legend-engine to 3.35.1

- pom.xml
Update legend-engine to 4.1.0 and legend-pure to 4.1.0
> Update legend-engine to 4.1.0 and legend-pure to 4.1.0

- pom.xml
Update legend-engine to 4.2.0 and legend-pure to 4.2.1
> Update legend-engine to 4.2.0 and legend-pure to 4.2.1

- legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-mapping-with-testTestSuites/entities/execution/RelationalMapping.json
update the json with the property name for mapping test data which has been refactored/ changed
Engine PR : https://github.com/finos/legend-engine/pull/1466 (already merged)
> fix test for mapping test suite

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabVersionApi.java
Remove the check that a revision has already been released when creating a new version.
> Remove check that a revision has already been released when creating a new version

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
Improve error handling when getting a project. Specifically, return a 404 if a GitLab project is found which is not a Legend SDLC project. Previously, a 500 was returned in this case. In passing, do some code clean up in GitLabProjectApi.
> Improve error handling when getting a project

- pom.xml
> Upgrade legend-engine version

- pom.xml
> update Engine 4.5.0

- legend-sdlc-generation-file/src/test/resources/ArtifactGenerationFactoryTestData.json
- legend-sdlc-version-package-maven-plugin/src/test/resources/entity-path-transformer-test-resources/entities/model/func/MyFunction_ComplexClass_1__String_1_.json
> Fix function names in tests

- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/TestableTestCase.java
- pom.xml
- depends on https://github.com/finos/legend-engine/pull/1689
> reuse compiled pureModel to run testable tests + update legend engine

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/version/VersionId.java
- legend-sdlc-model/src/test/java/org/finos/legend/sdlc/domain/model/version/TestVersionId.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/TestBaseGitLabApi.java
- legend-sdlc-version-package-maven-plugin/src/main/java/org/finos/legend/sdlc/versions/VersionQualifiedPackageMojo.java
- legend-sdlc-version-package-maven-plugin/src/test/java/org/finos/legend/sdlc/versions/TestEntityPathTransformer.java
- legend-sdlc-version-package-maven-plugin/src/test/java/org/finos/legend/sdlc/versions/TestVersionQualifiedPackageMojo.java
Add method for checking if a string is a valid version id string and fix BaseGitLabApi.isVersionTagName.
> Add method for checking if a string is a valid version id string

- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- pom.xml
> Upgrade Legend dependencies

- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithPureOneByteParam.generated.java
- legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithZeroManyByteParam.generated.java
- legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithZeroOneByteParam.generated.java
- legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/ModelToModelServiceWithPureOneByteParam.json
- legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/ModelToModelServiceWithZeroManyByteParam.json
- legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/ModelToModelServiceWithZeroOneByteParam.json
Add support for byte data type
> Add support for byte data type

- pom.xml
update legend engine to 4.12.1 and legend pure to 4.5.2
> update legend engine to 4.12.1 and legend pure to 4.5.2

- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/invalid/TestMultiSection.pure
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping.pure
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_full.json
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_reduced.json
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping.pure
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_full.json
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_reduced.json
- pom.xml
> bump engine@4.13.3

- legend-sdlc-generation-model-maven-plugin/pom.xml
- pom.xml
> Upgrade build plugins

- pom.xml
Update:
- legend-engine to 4.14.1
- legend-pure to 4.5.3
- legend-shared to 0.23.6
> bump engine@4.14.1

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java
Ensure we include any error message from GitLab for review errors
> Ensure we include any error message from GitLab for review errors

- legend-sdlc-server/pom.xml
Do not create a dependency reduced pom for legend-sdlc-server
> Do not create a dependency reduced pom for legend-sdlc-server

- pom.xml
Upgrade nexus-staging-maven-plugin to 1.6.13
> Upgrade nexus-staging-maven-plugin to 1.6.13

- legend-sdlc-test-generation-maven-plugin/src/test/resources/test-entities/entities/execution/RelationalMapping.json
- legend-sdlc-test-generation/src/test/resources/entities/execution/RelationalMapping.json
- legend-sdlc-test-utils/src/test/resources/entities/execution/RelationalMapping.json
- pom.xml
Depends on https://github.com/finos/legend-engine/pull/1600
> update engine@4.15.4/pure@4.5.5 and handle mapping testable improvements

- pom.xml
Pick h2 version transitively from engine/pure
> Pick h2 version transitively from engine/pure

- legend-sdlc-test-generation-maven-plugin/src/test/resources/test-entities/entities/execution/RelationalMapping.json
- legend-sdlc-test-generation/src/test/resources/entities/execution/RelationalMapping.json
- legend-sdlc-test-utils/src/test/resources/entities/execution/RelationalMapping.json
- pom.xml
updates legend-engine-4.15.9 
updates tests to handle changes from https://github.com/finos/legend-engine/pull/1915
> update engine@4.15.9 and update mapping tests

- legend-sdlc-test-generation-maven-plugin/src/test/resources/test-entities/entities/execution/RelationalMapping.json
- legend-sdlc-test-generation/src/test/resources/entities/execution/RelationalMapping.json
- legend-sdlc-test-utils/src/test/resources/entities/execution/RelationalMapping.json
- pom.xml
> Revert "update engine@4.15.9 and update mapping tests"

- pom.xml
> Uptick engine to 4.17.0

- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java
Improve handling of extensions in ServiceExecutionGenerator. Previously, thread safety was achieved by instantiating extensions independently for each service plan generation. Now the extensions are instantiated once for all services, and thread safety is achieved by initializing them prior to using them in (possibly parallel) plan generation.
> Improve handling of extensions in ServiceExecutionGenerator

- pom.xml
> update engine to 4.22.1

- pom.xml
Update legend-engine and legend-pure version
> Update legend-engine and legend-pure version

- pom.xml
Update legend engine to 4.25.2 and legend-pure to 4.5.12
> Update legend engine to 4.25.2 and legend-pure to 4.5.12

- README.md
Update README.md about building with JDK 17
> Update README.md about building with JDK 17

- pom.xml
Bump legend engine to 4.27.0 and legend pure to 4.5.15
> Bump engine and pure

- pom.xml
Update engine to 4.28.0 and pure to 4.6.0
> Update engine to 4.28.0 and pure to 4.6.0

- pom.xml
> Update engine to 4.28.2

- pom.xml
Update legend-engine to 4.29.0 and legend-pure to 4.7.0
> Update legend-engine to 4.29.0 and legend-pure to 4.7.0

- .github/workflows/test-result.yml
Upgrade publish-unit-test-result-action from v1.35 to v2.10.0
> Upgrade publish-unit-test-result-action to v2.10.0

- .github/workflows/build.yml
Upgrade actions/cache, actions/checkout, and actions/setup-java to versions 3, 4, and 3.13.0
> Upgrade actions/cache, actions/checkout, and actions/setup-java

- pom.xml
update legend engine to 4.30.3
> update legend engine to 4.30.3

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/accessRole/UserPermission.java
- legend-sdlc-server-fs/src/main/java/org/finos/legend/sdlc/server/api/project/FileSystemProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/project/project/ProjectsResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApiTestResource.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerProjectApis.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectApi.java
Added API to retrieve all members associated with a project along with the member role
> Added API to retrieve all members associated with a project along with the member role

- legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/configuration/ProjectConfiguration.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/application/project/UpdateProjectConfigurationCommand.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectConfigurationUpdater.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureV13Factory.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/SimpleProjectConfiguration.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendJUnitTestGenerationPluginMavenHelper.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureV13.java
- legend-sdlc-test-generation-maven-plugin/src/main/java/org/finos/legend/sdlc/test/junit/JUnitTestGenerationMojo.java
- legend-sdlc-test-generation-maven-plugin/src/test/java/org/finos/legend/sdlc/test/junit/TestJUnitTestGenerationMojo.java
- legend-sdlc-test-generation-maven-plugin/src/test/resources/dependencies-entities/entities/model/A.json
- legend-sdlc-test-generation-maven-plugin/src/test/resources/dependencies-entities/entities/model/MyMapping.json
- legend-sdlc-test-generation-maven-plugin/src/test/resources/generated/java/org/finos/legend/sdlc/test/junit/junit4/model/TestMyMapping.java
- adds runsDependencyTests in project configuration
- uses above flag in Test Generation to generate tests for dependencies when set.
- associated studio changes https://github.com/finos/legend-studio/pull/2734
> add runDependencyTests option in JunitGenerationMojo and set it via project config

- pom.xml
Update pure @4.10.0 and engine @4.33.3
> Update pure @4.10.0 and engine @4.33.3

- pom.xml
Update legend engine to 4.33.5
> Update legend engine to 4.33.5

- pom.xml
update legend-engine to 4.33.6
> update legend-engine to 4.33.6

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java
Fix exception message for Invalid Project Type
> Fix Invalid Project Type Exception

- pom.xml
> Update engine @4.35.3

- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestPureEntitySerializer.java
Prepare for parser to provide valid tokens
> Prepare for parser to provide valid tokens

- legend-sdlc-language-pure-compiler/pom.xml
- legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/PureTestHelper.java
Allow more configuration options in PureModelBuilder. Also, fix some dependency issues in its module.
> Improvements to PureModelBuilder

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
- legend-sdlc-test-utils/pom.xml
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/AbstractTestableTest.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/TestableTestCase.java
- pom.xml
> Uptick versions

- legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
- legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureModelContextDataBuilder.java
Allow supplying EntityToPureConverter to PureModelBuilder
> Allow supplying EntityToPureConverter to PureModelBuilder

- legend-sdlc-generation-service-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/service/ServicesGenerationMojo.java
- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/PureTestHelper.java
- pom.xml
Upgrade to Engine 4.38.0 and Pure 5.1.0
> Upgrade to Engine 4.38.0 and Pure 5.1.0

- .github/workflows/build.yml
- .github/workflows/clean-after-failed-release.yml
- .github/workflows/docker.yml
- .github/workflows/gitlab-com-integration-test.yml
- .github/workflows/gitlab-docker-int-test-latest-twelve.yml
- .github/workflows/gitlab-docker-int-test-latest.yml
- .github/workflows/gitlab-docker-int-test-nightly.yml
- .github/workflows/legend-stack-release.yml
- .github/workflows/ossrh-close-staging-repo.yml
- .github/workflows/release.yml
- pom.xml
Upgrade legend-sdlc to build with JDK 21. In passing, upgrade workflow actions to the latest versions.
> Upgrade legend-sdlc to build with JDK 21

- pom.xml
> Uptick engine@4.38.4

- pom.xml
Upgrade legend-engine to 4.39.0 and legend-pure to 5.1.3
> Upgrade legend-engine to 4.39.0 and legend-pure to 5.1.3

- pom.xml
Update legend-engine to 4.39.1
> Update legend-engine to 4.39.1

- pom.xml
> engine@4.40.3

- legend-sdlc-generation-service-maven-plugin/pom.xml
- legend-sdlc-generation-service/pom.xml
- legend-sdlc-test-utils/pom.xml
- pom.xml
Upgrade legend-engine to 4.41.0 and legend-pure to 5.2.1
> Upgrade legend-engine to 4.41.0 and legend-pure to 5.2.1

- pom.xml
Update dependency management for org.slf4j:jul-to-slf4j
> Update dependency management for org.slf4j:jul-to-slf4j

- pom.xml
Update pure@5.2.2, engine@4.42.3
> Update pure@5.2.2, engine@4.42.3

- pom.xml
> update to engine patch 4.42.5

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java
improve invalid artifact id error message
> improve invalid artifact id error message

- pom.xml
> update engine @4.46.0

- pom.xml
fix dependency convergence for HikariCP
should be merged after engine PR https://github.com/finos/legend-engine/pull/2881
> Fix dependency and update engine @4.47.1 and pure @5.8.1

- pom.xml
> Upgrade jsoup to 1.17.2

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabAuthorizer.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabAuthorizerManager.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabKerberosSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOAuthAuthenticator.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOidcSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabPersonalAccessTokenSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabTokenManager.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabTokenResponse.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabUserContext.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/KerberosGitLabAuthorizer.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiTestSetupUtil.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/auth/TestGitLabSession.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/auth/TestGitLabTokenManager.java
The PR contains two changes;
- OAuth implicit grant flow is being demised
- OAuth refresh token flow is being implemented
> update oauth flow for Gitlab 15 compatibility

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOAuthAuthenticator.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabTokenManager.java
fix minor bugs for smooth transition to gitlab 15 oauth flow
> fix minor bugs for smooth transition to gitlab 15 oauth flow

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOidcSession.java
update gitlab implementation for oidc flow, allowing refreshes
> update gitlab implementation for oidc flow, allowing refreshes

- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java
- legend-sdlc-generation-model-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/model/ModelGenerationMojo.java
- legend-sdlc-generation-service-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/service/ServicesGenerationMojo.java
- legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/PureTestHelper.java
Details on performance of parallelism: https://github.com/finos/legend-engine/pull/2949
> Enable parallel compiler on SLDC mojos

- legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
Pass thread context class loader when no explicit class loader is pass
> Pass thread context class loader when no explicit class loader is pass

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabUserContext.java
setting expiry and refresh token for isAuthorised api
> setting expiry and refresh token for isAuthorised api

- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- pom.xml
Upgrade legend engine version and incorporate changing engine Variable _class to PackageableElementPointer
> Upgrade legend engine version and incorporate changing engine Variable _class to PackageableElementPointer

- pom.xml
Bump engine and shared versions
> Bump engine and shared

- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabAuthorizer.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabAuthorizerManager.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabKerberosSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOAuthAuthenticator.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOidcSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabPersonalAccessTokenSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabSession.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabTokenManager.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabTokenResponse.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabUserContext.java
- legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/KerberosGitLabAuthorizer.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiTestSetupUtil.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/auth/TestGitLabSession.java
- legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/auth/TestGitLabTokenManager.java
Demising oauth implicit flow for gitlab 15 compatibility
> Demising oauth implicit flow for gitlab 15 compatibility

- pom.xml
> Upgrade legend-engine@4.53.8

- pom.xml
Upgrade legend-pure@5.14.0, legend-shared@0.25.6 and engine@4.54.0
> Upgrade legend-pure@5.14.0, legend-shared@0.25.6 and engine@4.54.0

- pom.xml
Update pom.xml for engine release
> Update pom.xml for engine release

- pom.xml
Update pom.xml for engine release
> Update pom.xml for releease

- pom.xml
Upgrade legend-engine to 4.63.1 and legend-shared to 0.25.7
> Upgrade legend-engine to 4.63.1 and legend-shared to 0.25.7

- pom.xml
Upgrade legend-engine to 4.63.2
> Upgrade legend-engine to 4.63.2

- legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/associations/Employment.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Address.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/EntityWithAddresses.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Firm.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Person.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-mixed-model/model/domain/classes/EntityWithAddresses.json
- legend-sdlc-entity-maven-plugin/src/test/resources/simple-mixed-model/model/domain/classes/Firm.json
- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/associations/Employment.json
- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/classes/Address.json
- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/classes/EntityWithAddresses.json
- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/classes/Firm.json
- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/classes/Person.json
- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- legend-sdlc-model/src/test/java/org/finos/legend/sdlc/domain/model/TestTools.java
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/association/TestAssociation_full.json
- legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/class/TestClass_full.json
- pom.xml
> Update the platform

- legend-sdlc-entity-maven-plugin/src/test/resources/single-file-json-model/entities/model/domain/stores/TestDatabase.json
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java
- legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/artifact/ArtifactGenerationFactory.java
- legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationFactory.java
- legend-sdlc-generation-file/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationFactory.java
- legend-sdlc-generation-model-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/model/ModelGenerationMojo.java
- legend-sdlc-generation-model/src/main/java/org/finos/legend/sdlc/generation/model/ModelGenerationFactory.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
- legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/EntityToPureConverter.java
- legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureEntitySerializer.java
- legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureModelContextDataBuilder.java
- legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureToEntityConverter.java
- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/PureProtocolHelper.java
- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestEntityToPureConverter.java
- legend-sdlc-protocol/src/test/java/org/finos/legend/sdlc/protocol/TestProtocolToEntityConverter.java
- legend-sdlc-test-generation/src/main/java/org/finos/legend/sdlc/test/junit/AbstractTestClassGenerator.java
- legend-sdlc-test-generation/src/main/java/org/finos/legend/sdlc/test/junit/JUnitTestGenerator.java
- legend-sdlc-test-generation/src/main/java/org/finos/legend/sdlc/test/junit/TestableTestGenerator.java
- legend-sdlc-test-generation/src/test/java/org/finos/legend/sdlc/test/junit/AbstractTestClassGeneratorTest.java
- legend-sdlc-test-generation/src/test/java/org/finos/legend/sdlc/test/junit/TestTestableTestGenerator.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/AbstractMappingTest.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/AbstractPureTest.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/AbstractServiceTest.java
- legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/PureTestHelper.java
- pom.xml
> Upgrade Dependencies

- legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/artifact/ArtifactGenerationFactory.java
- legend-sdlc-generation-model/src/test/java/org/finos/legend/sdlc/generation/model/TestModelGenerationFactory.java
- legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java
- legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java
- legend-sdlc-language-pure-compiler/src/test/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/TestPureModelBuilder.java
- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestEntityToPureConverter.java
- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestPureModelContextDataBuilder.java
- legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestPureToEntityConverter.java
- legend-sdlc-protocol/src/test/java/org/finos/legend/sdlc/protocol/TestEntityToProtocolConverter.java
- legend-sdlc-protocol/src/test/java/org/finos/legend/sdlc/protocol/TestProtocolToEntityConverter.java
- pom.xml
Update to latest Engine version
> Update to latest Engine version

- pom.xml
Upgrade Pure@5.30.0, Engine @4.68.0
> Upgrade Pure@5.30.0, Engine @4.68.0

- pom.xml
Updating pure and engine versions
> Update Pure and Engine versions

- legend-sdlc-generation-file-maven-plugin/pom.xml
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/ReducedProjectConfiguration.java
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentExtensionInfo.java
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentMetaDataMojo.java
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentMetadata.java
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentMojo.java
- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestBasicClassDeployExtension.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestBasicEnumDeployExtension.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestDeploymentMetadataMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestDeploymentMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/resources/META-INF/services/org.finos.legend.engine.deployment.model.DeploymentExtension
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/deploy/cityDeployment.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/deploy/classDeployTestDeployment.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/deploy/deploymentWithEntities.json
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/deploy/validateWithEntities.json
- pom.xml
- setup deploy mojo runner + deployment extension metadata
> setup deploy mojo runner + deployment extension metadata

- pom.xml
Upgrade Legend-Pure@5.34.0, Legend-Engine@4.70.1
> Upgrade Legend-Pure@5.34.0, Legend-Engine@4.70.1

- pom.xml
> Upgrade engine@4.71.1

- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestBasicEnumDeployExtension.java
- legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/deployment/TestDeploymentMojo.java
- legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/deploy/deploymentWithEntities.json
minor updates to handling deployment responses
> minor updates to handling deployment responses

- pom.xml
Update nexus-staging-maven-plugin
> Update nexus-staging-maven-plugin version

- pom.xml
This reverts commit 7c51d8dcf165238f057a818400e7870d7d8a2f8a.
> Revert "Update nexus-staging-maven-plugin version (#875)"

- legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/deployment/DeploymentMojo.java
add more logging to deploy mojo #878
> add more logging to deploy mojo

- pom.xml
update to legend-engine@4.73.1
> update to legend-engine@4.73.1

- pom.xml
Upgrade legend-engine@4.75.3 and legend-pure@5.40.0
> Upgrade legend-engine@4.75.3 and legend-pure@5.40.0

- pom.xml
Bug Fix
Upgrade a dependency to fix a vulnerability issue.
No
> upgrade wiremock to v2.35.2

- pom.xml
> Add back dependencies

- pom.xml
> Remove Exclusions

- pom.xml
revert wiremock upgrade
reverting PR: https://github.com/finos/legend-sdlc/pull/884
> Revert wiremock upgrade + Upgrade pure@5.41.0, engine@4.76.0

- pom.xml
Update Engine Version @ 4.77.1
> Update Engine Version @ 4.77.1

- pom.xml
legend-engine@4.81.0 and legend-pure@5.45.0
> legend-engine@4.81.0 and legend-pure@5.45.0

- pom.xml
subsequence update for wiremock@2.35.2
> subsequence update for wiremock@2.35.2

- pom.xml
Upgrade legend-engine to 4.84.0, legend-pure to 5.47.0, and legend-shared to 0.26.0.
> Upgrade legend-engine@4.84.0, legend-pure@5.47.0, legend-shared@0.26.0

- pom.xml
Upgrade legend-engine to 4.84.1
> Upgrade legend-engine@4.84.1

- pom.xml
Update engine and pure versions
> Update engine and pure versions

- .github/workflows/build.yml
Switch from deploy to install for master branch builds, as deploying snapshots is currently not possible
> Switch from deploy to install for master branch builds

- pom.xml
updated legend-engine version and legend-pure versions
> Update pom.xml with legend-engine@4.89.0 and legend-pure@5.51.2

- pom.xml
> Upgrade legend-engine@4.93.0

- pom.xml
Update legend-engine@4.96.0, legend-pure@5.55.0
> Update legend-engine@4.96.0, legend-pure@5.55.0

- pom.xml
update legend-engine and legend-pure versions
> update legend-engine and legend-pure versions

- pom.xml
Uptick leged-engine to 4.99.0 and legend-pure to 5.59.0
> Uptick legend-engine to 4.99.0 and legend-pure to 5.59.0

- pom.xml
> Upgrade JodaTime@2.10.14
