pom.xml
The 4.0.5 metrics version is incompatible with the version of the HealthCheck module and results in NoSuchMethodErrors during ser/deser of the Healthcheck result.
=> Upgrade Dropwizard metrics to 4.1.6

.github/workflows/docker.yml, legend-sdlc-server/Dockerfile
Add Docker security scan.
Also update `Dockerfile` to use a fixed version of `openjdk` base image instead of `openjdk:11` which is equivalent to the `latest` tag. Otherwise, we are not confident of which `openjdk` image we're using and thus, making debugging harder - For example, see https://github.com/aquasecurity/trivy/issues/885
Context https://github.com/finos/legend/issues/360
=> Add Docker security scan

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabUserContext.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/resources/GitLabAuthResource.java
Send 403 instead of 401 when there is an issue with authentication or authorization with GitLab (but not with Legend SDLC). Sending a 401 confuses client browsers, which will interpret it as an authentication issue with Legend SDLC itself.
=> Send 403 instead of 401 when there is an auth issue with GitLab

legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/AbstractGitLabServerApiTest.java, pom.xml
Configure failsafe v3-m5 to measure surefire module path bug.
=> Configure failsafe v3-m5 to measure surefire module path bug

legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureEntitySerializer.java, legend-sdlc-protocol-pure/src/test/java/org/finos/legend/sdlc/protocol/pure/v1/TestPureEntitySerializer.java, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/association/TestAssociation_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/class/TestClass_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/enumeration/TestEnumeration_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_reduced.json
This reverts commit c808552bf5b7e512370f8232c9a34bb0a0fdbbd3.
Reverting as the corresponding change in legend-engine https://github.com/finos/legend-engine/pull/339 is incomplete and requires relational parse tree walkers to be updated to handle no source information
=> Revert "Remove SourceInformation from serialized entities (#245)"

.github/workflows/gitlab-docker-int-test-latest-twelve.yml, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java
- Make GitLab integration tests for three versions (nightly, latest, latest-12) Docker images PR and master push optional checks.
- Relax merge check on certain integration tests for better visibility.
=> Make GitLab Docker tests as PR and master push optional checks.

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/test/TestModelBuilder.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/utils/TestModelBuilderTest.java
added functions to test model builder allows to build entities for tests for upstream project with provided:
- workspace and revision id (left for **backward compatibility**, user workspace is used by default)
- workspace with type and revision id - allows to use group workspace or user workspace
- version id
- revision id  (from main branch)
also tests were edited to make sure that introduced functions are working as expected
=> Enhance TestModelBuilder with more ways to build entities

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
We need to bind test model builder in Abstract base module if we want to use inject that class in future
=> Bind TestModelBuilder class

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/depot/api/DepotMetadataApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/depot/api/MetadataApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/test/TestModelBuilder.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/metadata/InMemoryMetadataApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/utils/TestModelBuilderTest.java
- Make sure to throw an error if user mistakenly specified upstream project as downstream and vice versa
- Add support for not directly depend projects
- Make sure TestModelBuilder doesn't throw ConcurrentModificationException
=> Improve error handling in TestModelBuilder and add more tests

.github/workflows/build.yml, legend-sdlc-server/pom.xml
Add Docker snapshot build to be used for integration testing of Legend application stack. The immediate usage right now is for Studio E2E testing.
=> add Docker snapshot build for integration testing

legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/BaseServer.java, legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/config/CORSConfiguration.java, legend-sdlc-server-shared/src/main/java/org/finos/legend/sdlc/server/config/ServerConfiguration.java
I'm trying to create end-to-end test for Studio pointing at SDLC and trying to bypass authentication by using private access token via `org.finos.legend.server.pac4j.gitlab.GitlabPersonalAccessTokenClient`. The `Pac4j` config of this looks like this
```yml
pac4j:
callbackPrefix: /api/pac4j/login
clients:
- org.finos.legend.server.pac4j.gitlab.GitlabPersonalAccessTokenClient:
headerTokenName: legend-test-pat
scheme: https
gitlabHost: gitlab.com
gitlabApiVersion: v4
bypassPaths:
- /api/info
```
I found out that If I'm trying to use this from a browser, I also need to specify `legend-test-pat` as an `allowed header` otherwise, I would bump into CORS issue. The logic for this is:
https://github.com/finos/legend-sdlc/blob/fda3d8f6b82001fc7e31ec9c016c4087feb71a00/legend-sdlc-server-shared/src/ma …
=> support configuring CORS filter allowed headers

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/BaseLegendSDLCServer.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspacePureModelContextDataResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceRevisionPureModelContextDataResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspacePureModelContextDataResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceRevisionPureModelContextDataResource.java
Configure the DropWizard ObjectMapper with Pure protocol extensions so that PureModelContextData objects are properly serialized to JSON. Add APIs for getting PureModelContextData from user and group workspaces and revisions.
=> Fix and extend PureModelContextData resources

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java
This is a bug fix to prevent "actions cannot be null or empty" response from gitlab when committing
=> Don't try to commit empty content

legend-sdlc-generation-service/pom.xml, legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/main/resources/generation/service/ServiceExecutionClassGenerator.ftl, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelService.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceMulti.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithMultipleParams.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithNMultiplicityParam.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/ModelToModelServiceWithParam.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/RelationalService.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/RelationalServiceWithParams.generated.java, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/ModelToModelServiceWithNMultiplicityParam.json, pom.xml
This PR aims to reduce execution related code on the service generation, keeping only the description of the service, and letting legend-egine control how to execute.
It also move code generation to free mark, which should help developers follow what code is generated and how the code looks.
=> Generates ServiceRunner with newer execute and run APIs

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/dependency/DependenciesApiImpl.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectsResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/AbstractGitLabServerApiTest.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectApi.java
Allow setting limit when fetching projects (/projects endpoint). This would be useful to make the API typeahead friendly, for more context, see https://github.com/finos/legend-studio/issues/408
=> allow setting limit when fetching projects

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
Enable `simple` [mode](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) when fetching projects to improve performance. @kevin-m-knight-gs did some profiling with this and it did show certain sign of improvements.
This change is covered by `IntegrationTestGitLabProjectApis.runGetProjectTest()` to prove that even in `simple` mode all fields we need for constructing `Project` object are still available.
=> speed up fetching projects by enabling `simple` mode

legend-sdlc-generation-service/pom.xml, legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java
Ensure we use only \n for line breaks in generated service executor Java code. This ensures that we have only one type of line break in each file. It also ensures consistency of line breaks across different environments. This in turn ensures that tests will work consistently across environments.
=> Ensure we use only \n for line breaks in generated service executor code

README.md
Update README.md to add some clarifications about redirect URIs for GitLab applications. In particular, to suggest that people use both 127.0.0.1 and localhost for testing purposes.
=> Update README.md to clarify about redirect URIs for GitLab applications

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
Delete workspace created for project structure if project update fails in import project endpoint.
Extract the logic for deleting the workspace into a method to remove code duplication.
=> [ISSUE#394] Add fix to delete workspace if project update fails in import project endpoint 

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabBuildApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitlabWorkflowApi.java
I have observed that by setting `limit` as the `itemsPerPage` in `fetch...` APIs, their performance actually degrade a lot. See the video of Studio loading projects with `limit=3`. See the videos below:
https://user-images.githubusercontent.com/13574879/162664509-330919f5-d93d-44ef-af02-ed1a882bc545.mov
https://user-images.githubusercontent.com/13574879/162664513-b6c9bf95-f2e9-43d7-940b-12e1ef14ad47.mov
=> fix API performance problem with limit being used as items per page

legend-sdlc-test-utils/pom.xml
Exclude legend-pure-code-compiled-platform-java from legend-sdlc-test-utils so that it does not conflict with platform metadata brought in via extension collections.
=> Exclude legend-pure-code-compiled-platform-java from legend-sdlc-test-utils

pom.xml
Next Legend Engine will cause some enforcer issues around Jetty IO
RE: https://github.com/finos/legend-engine/pull/681
=> Define Jetty-IO version to avoid enforcer problems

legend-sdlc-test-reports/pom.xml, pom.xml
Restrict the maven enforcer rules that apply in legend-sdlc-test-reports. The enforcer rules have little to no value in that module, since its sole purpose is to aggregate test results from other (substantive) modules. And the dependency convergence rule, in particular, was causing the build to fail in maven 3.6.
=> Restrict the maven enforcer rules that apply in legend-sdlc-test-reports

legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/TestService.json, legend-sdlc-test-utils/src/test/resources/legend-sdlc-test-service-with-testSuites/entities/testTestSuites/TestService2.json
We added ability for users to use a serializationFormat with their service test.
Unfortunately we missed using the format for graphfetch queries and hence could go ahead without making this change. We are fixing that here (https://github.com/finos/legend-engine/pull/799) and to support that will need this change.
This change here uses that ability (uses PURE serializationFormat)
=> Fix testSuite test with correct serializationFormat

legend-sdlc-entity-maven-plugin/pom.xml, legend-sdlc-entity-maven-plugin/src/test/java/org/finos/legend/sdlc/entities/PureDomainDeserializer.java, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/associations/Employment.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Address.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/EntityWithAddresses.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Firm.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/classes/Person.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-json-model/entities/model/domain/enums/AddressType.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-mixed-model/model/domain/classes/EntityWithAddresses.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-mixed-model/model/domain/classes/Firm.json, legend-sdlc-entity-maven-plugin/src/test/resources/simple-mixed-model/model/domain/enums/AddressType.json, legend-sdlc-protocol-pure/src/main/java/org/finos/legend/sdlc/protocol/pure/v1/PureEntitySerializer.java, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/association/TestAssociation_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/class/TestClass_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/class/TestClass_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/enumeration/TestEnumeration_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_full.json
I believe we have properly fixed the problem in `engine` with `returnSourceInformation=false` flag in https://github.com/finos/legend-engine/pull/692 so it should be safe to make use of this to:
- reduce entity size
- improve SDLC response time due to lower traffic load
=> remove source information on Pure parsing to optimize storage size

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructurePlatformExtensions.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectPlatformsConfiguration.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/config/TestProjectPlatformsConfiguration.java, legend-sdlc-server/src/test/resources/META-INF/maven/org.finos.legend.sdlc.test/test-extension-collection-generation/pom.properties
Resolve platforms configuration at server startup so that configuration issues are discovered as soon as possible. Also, add tests for the platforms configuration, particular the resolution of versions from packages.
=> Resolve platforms config at server startup

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/GitLabConfiguration.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/GitLabProjectId.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/TestGitLabProjectId.java
Validate prefix when parsing project ids. Previously, if someone used the wrong prefix in a project id, it would be ignored. The integer part of the id was extracted and used. This can lead to people potentially getting the wrong project in cases where there are multiple servers that use different id prefixes. Now the server will return a 400 if the user uses the wrong id prefix.
=> Validate prefix when parsing project ids

legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/configuration/ArtifactGeneration.java, legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/configuration/ArtifactType.java, legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/configuration/ProjectConfiguration.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectConfigurationApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectConfigurationApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectConfigurationUpdateBuilder.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/SimpleProjectConfiguration.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/MultiModuleMavenProjectStructure.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ConfigurationResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectConfigurationApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/domain/api/InMemoryProjectConfiguration.java
Deprecate old style artifact generations. These have been replaced by a new framework for generations.
=> Deprecate (old style) artifact generations

pom.xml
Upgrade maven libraries to 3.8.6. This should alleviate [CVE-2022-29599](https://www.mend.io/vulnerability-database/CVE-2022-29599).
=> Upgrade maven libraries to 3.8.6

legend-sdlc-server/Dockerfile
Update Dockerfile to use openjdk:11.0.16-bullseye
=> Update Dockerfile to use openjdk:11.0.16-bullseye

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java
Fix bug in project import where workspace information is dropped. In passing, fix a validation that workspace type and access type are present when workspace id is present.
=> Fix bug in project import where workspace information is dropped

legend-sdlc-generation-file-maven-plugin/pom.xml, legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestSimpleEnumArtifactGenerationExtension.java, legend-sdlc-generation-file-maven-plugin/src/test/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/City/test-enumeration-generation/SomeTestOutput.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/Country/test-enumeration-generation/SomeTestOutput.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/IncType/test-enumeration-generation/SomeTestOutput.txt, legend-sdlc-generation-file/pom.xml, legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/artifact/ArtifactGenerationFactory.java, legend-sdlc-generation-file/src/main/java/org/finos/legend/sdlc/generation/artifact/ArtifactGenerationResult.java
- Related to https://github.com/finos/legend-sdlc/issues/504
- `BREAKING` depends on https://github.com/finos/legend-engine/pull/833 and https://github.com/finos/legend-engine/pull/900
- handles ArtifactGenerationExtensions and serializes the result to the output directory as part of the file maven plugin
=> handle ArtifactGenerationExtensions 

legend-sdlc-server/Dockerfile, legend-sdlc-server/src/main/resources/docker/config/config.json
This PR adds a set of default configuration files into the server Docker image. 
This simplifies the running of the Docker images. Users can simply run the container by passing configuration values as environment variables instead of having to manage the configuration files.
=> Include default configuration files in Docker image

legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/City/test-enumeration-generation/SomeTestOutput.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/Country/test-enumeration-generation/SomeTestOutput.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/IncType/test-enumeration-generation/SomeTestOutput.txt
Fixes bug when no generation specification is found but there is exists artifact generation
=> handle artifact generations when no generation specification is present

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/SimpleProjectConfiguration.java
Fix a typo in SimpleProjectConfiguration.newConfiguration that caused problems when deserializing a project.json file containing a value for platformConfigurations.
=> Fix a typo in SimpleProjectConfiguration.newConfiguration

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/test/TestModelBuilder.java
Fix exception handling in TestModelBuilder by ensuring that LegendSDLCServerExceptions get propagated without being wrapped.
=> Fix exception handling in TestModelBuilder

legend-sdlc-server/src/main/resources/docker/config/config.json, legend-sdlc-server/src/test/resources/config-test.yaml
Specifying session cookie name to help with local development (when we have multiple Legend applications)
See https://stackoverflow.com/questions/16789495/two-applications-on-the-same-server-use-the-same-jsessionid
=> add `sessionCookie` to test and Docker config to help with development using docker-compose

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/entity/EntityAccessContext.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/BackupWorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/BackupWorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ComparisonReviewEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ConflictResolutionWorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ConflictResolutionWorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/EntityAccessResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupBackupWorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupBackupWorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupConflictResolutionWorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupConflictResolutionWorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/GroupWorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectRevisionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceEntitiesResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/WorkspaceRevisionEntitiesResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryEntityApi.java
Improve endpoints for pulling entities by adding one more parameter whose default value is false to suppress errors from entity validations and only return the valid entities.
If value is true, it means that invalid entities are excluded.
If value is false, it means that endpoints will return an error if there are any invalid entities as before.
https://user-images.githubusercontent.com/73408381/193902405-4da6e9f6-f7ab-4afa-8468-9929ae18dbe6.mov
=> A comprehensive error handling strategy of pulling entities -- part I

pom.xml
This is to avoid using dependency wit new discovered [vulnerability](https://www.cve.org/CVERecord?id=CVE-2022-42889).
=> Bump apache commons text from 1.8 to 1.10.0

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/BaseGitLabApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/TestBaseGitLabApi.java
**1. Update Engine parser so that the function signature will be used for function.name
2. SDLC identifies the old style (use functionName as the file name) functions, then creates a new entity that has functionName as its path  
3. Studio will create a ‘Delete’ action to delete this kind of entity above, then do a ‘Create’ operation to correct the gitlab file name**
depends on https://github.com/finos/legend-engine/pull/759
=> support function overloading

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectConfigurationApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabApiWithFileAccess.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectConfigurationApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectConfigurationStatusReport.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectConfigurationResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectConfigurationApi.java
Related to finos/legend-studio#1329
=> Add endpoint to check the project configuration of gitlab project

legend-sdlc-server/Dockerfile
It seems that `openjdk` no longer publish docker images for jdk11 - https://github.com/docker-library/openjdk/issues/505
So per their recommendation, we are trying out the alternative - `eclipse-temurin`
=> update java Docker image to `eclipse-temurin:11.0.17_8-jdk-jammy`

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/review/ReviewApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabReviewApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewFilterResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsOnlyResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ReviewsResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryReviewApi.java
Add a path paramter to ​/projects​/{projectId}​/reviews which fetches the review from a sourceWorkspace
=> Add `sourceWorkspace` path parameter to reviews endpoint

legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java, legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceParamEnumClassGenerator.java, legend-sdlc-generation-service/src/main/resources/generation/service/ServiceParamEnumClassGenerator.ftl, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/model/Country.java, legend-sdlc-generation-service/src/test/java/org/finos/model/_enum/Country.java, legend-sdlc-generation-service/src/test/resources/generation/model/Country.generated.java, legend-sdlc-generation-service/src/test/resources/generation/model/_enum/Country.generated.java, legend-sdlc-generation-service/src/test/resources/generation/service/RelationalServiceWithEnumParams.generated.java, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/model/Country.json, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/model/RelationalMapping.json, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/model/SourcePerson.json, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/model/enum/Country.json, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/RelationalServiceWithEnumParams.json, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/store/MyDatabase.json
**What type of PR is this?**
Minor Enhancement
**What does this PR do / why is it needed ?**
During java generation, enum parameters of a service must be identified and the respective enum classes must be generated. Right now only generic types are supported, extending it to user-defined enum types (limited to only the ones used as parameters to services).
**Which issue(s) this PR fixes:**
Users can't merge their changes with services having enums as parameters as the gitlab build fails saying Unknow parameter type which stops from registering the service on PROD. 
**Does this PR introduce a user-facing change?**
No
=> Generate jar for Services with Enums as Parameters

legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionClassGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/resources/generation/service/RelationalServiceWithEnumParams.generated.java, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/RelationalServiceWithEnumParams.json
Update the testcase to a service that takes in both enums and other primitive types as parameters.
=> Update test to include enums and generic service parameters

legend-sdlc-generation-file-maven-plugin/pom.xml, legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/ReducedProjectConfiguration.java, legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestFileGenerationMojo.java, legend-sdlc-generation-file-maven-plugin/src/test/java/org/finos/legend/sdlc/generation/file/TestSdlcInfoArtifactGenerationExtension.java, legend-sdlc-generation-file-maven-plugin/src/test/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/City/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/Country/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputs/model/IncType/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/City/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/Country/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-generation-file-maven-plugin/src/test/resources/org/finos/legend/sdlc/generation/file/allFormats/outputsNoGenerationSpecification/model/IncType/test-sdlcinfo-generation/SDLCInfo.txt, legend-sdlc-language-pure-compiler/pom.xml, legend-sdlc-language-pure-compiler/src/main/java/org/finos/legend/sdlc/language/pure/compiler/toPureGraph/PureModelBuilder.java
Adds the SDLC project groupId/artifactId/version to the SDLC metadata in the built PureModelContext for downstream consumption in ArtifactGenerationExtensions.
=> Add project metadata to PureModelContext in File Generation plugin

legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/FileGenerationMojo.java
Make the file generation plugin more lenient about duplicate files. Only throw an exception if there are duplicate files with different content. Allow duplicates if the content is the same, though log a warning.
=> Make the file generation plugin more lenient about duplicate files

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/tools/PagerTools.java
Fix an issue with PagerSpliterator in which it might skip the current page. Specifically, this would occur if the current page of the pager were not 0, such as if the pager had been advanced already.
=> Fix an issue with PagerSpliterator in which it might skip the current page

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/resources/GitLabAuthCheckResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/resources/GitLabAuthResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/BaseModule.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/UserContext.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/tools/SessionUtil.java, legend-sdlc-server/src/test/resources/config-sample.yaml
The /authorized endpoint used to return 503 if there was no user session.
With this change it returns false as expected.
=> Fixing the /authorized endpoint

legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/m2m/TestMapping_reduced.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_full.json, legend-sdlc-protocol-pure/src/test/resources/pure-entity-serializer-test/mapping/relational/TestMapping_reduced.json, pom.xml
Dataspace functionality created changes in MappingInclude protocol that need to be reflected in legend-sdlc
Depends on engine version that includes: https://github.com/finos/legend-engine/pull/1649
=> Update tests to align with MappingInclude changes in Legend-Engine

legend-sdlc-generation-file-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/file/ReducedProjectConfiguration.java
Implementing ProjectConfiguration was superfluous and caused deserialization problems when `platformConfigurations` was specified in project.json.
=> Refactored ReducedProjectConfiguration to no longer implement ProjectConfiguration

legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/resources/generation/service/RelationalServiceWithEnumParamsReused.generated.java, legend-sdlc-generation-service/src/test/resources/org/finos/legend/sdlc/generation/service/entities/service/RelationalServiceWithEnumParamsReused.json
Skip generating enum classes for service artifact if it exists already.
This is possible when we have two or more services having the same enum (with path to element) as a parameter.
=> Avoid duplicate enum class generations

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureV11Factory.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureV12Factory.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureV13Factory.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/AbstractLegendMavenPluginHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendEntityPluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendFileGenerationPluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendJUnitTestGenerationPluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendModelGenerationPluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendServiceExecutionGenerationPluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendTestUtilsMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/LegendVersionPackagePluginMavenHelper.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/MavenProjectStructure.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/maven/MultiModuleMavenProjectStructure.java, legend-sdlc-server/src/main/resources/META-INF/services/org.finos.legend.sdlc.server.project.ProjectStructureVersionFactory, legend-sdlc-server/src/main/resources/org/finos/legend/sdlc/server/gitlab/finos/finos-extension.yaml, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/finos/TestFinosGitlabProjectStructureExtension.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestMultiGenerationProjectStructure.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureFactory.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureStaticMethods.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureV11.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureV12.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureV13.java
Add project structure version 13. This leverages the new test generation plugin to replace the old JUnit 3 style test suite with JUnit 4 style test classes.
=> Add project structure version 13

legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java
Fix a bug in LegendSDLCTestSuiteBuilder in building the Pure model from entities. The building needs to be permissive about entities which do not correspond to Pure model elements.
=> Fix a bug in LegendSDLCTestSuiteBuilder

pom.xml
This reverts commit 4adca64e3941f96f91390ff6da305d2043006871. The legend-shared version used in legend-sdlc should be consistent with the one used in legend-engine. But legend-engine 4.12.1 uses legend-shared 0.23.3.
=> Revert "Update legend-shared to 0.23.5 (#645)"

pom.xml
Downgrade maven-source-plugin to 3.2.1. Using version 3.3.0 causes problems with the release. The newer version complains about the plugin being run multiple times.
=> Downgrade maven-source-plugin to 3.2.1

.github/workflows/build.yml, .github/workflows/gitlab-com-integration-test.yml, .github/workflows/gitlab-docker-int-test-latest-twelve.yml, .github/workflows/gitlab-docker-int-test-latest.yml, .github/workflows/gitlab-docker-int-test-nightly.yml, .github/workflows/legend-stack-release.yml, .github/workflows/ossrh-close-staging-repo.yml, .github/workflows/release.yml, pom.xml
Update legend-sdlc to make it compatible with JDK 17. Specifically, the previous version of guice was not compatible with JDK 17.
Also, set workflows to use JDK 17.
=> Make legend-sdlc compatible with JDK 17

legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/ProjectType.java, legend-sdlc-model/src/main/java/org/finos/legend/sdlc/domain/model/project/configuration/ProjectConfiguration.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/application/project/CreateProjectCommand.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/application/project/ImportProjectCommand.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/application/project/UpdateProjectConfigurationCommand.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectConfigurationUpdater.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/SimpleProjectConfiguration.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/ProjectsResource.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/resources/VersionsResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabComparisonApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabEntityApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectConfigurationApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabRevisionApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApiTestResource.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabProjectApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerProjectApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructure.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/project/TestProjectStructureStaticMethods.java
* For MANAGED projects functionality as is.
* For EMBEDDED projects do not create pom.xml files or trigger files created by extensions.
* For EMBEDDED disallow setting extensions version.
* Allow converting between EMBEDDED and MANAGED and vice versa.
=> Support EMBEDDED projects

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
Fix error when a workspace cannot be found to make sure a 404 status is returned
=> Fix error when a workspace cannot be found

legend-sdlc-generation-service-maven-plugin/src/main/java/org/finos/legend/sdlc/generation/service/ServicesGenerationMojo.java, legend-sdlc-generation-service/src/main/java/org/finos/legend/sdlc/generation/service/ServiceExecutionGenerator.java, legend-sdlc-generation-service/src/test/java/org/finos/legend/sdlc/generation/service/TestServiceExecutionGenerator.java, legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/LegendSDLCTestSuiteBuilder.java, legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/LegacyMappingTestCase.java, legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/LegacyServiceTestCase.java, legend-sdlc-test-utils/src/main/java/org/finos/legend/sdlc/test/junit/pure/v1/PureTestHelper.java
Change parallelization of service execution generation to give better control. In particular, try to terminate tasks as quickly as possible in case one completes abnormally (by error or cancellation).
In passing, fix the handling of extensions.
=> Change parallelization of service execution generation

legend-sdlc-server-fs/src/main/java/org/finos/legend/sdlc/server/api/project/FileSystemProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/domain/api/project/ProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabProjectApi.java, legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabComparisonApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabEntityApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabProjectConfigurationApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabRevisionApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/docker/IntegrationTestGitLabWorkspaceApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerComparisonApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerEntityApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerProjectConfigurationApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerRevisionApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/gitlab/api/server/TestGitLabServerWorkspaceApis.java, legend-sdlc-server/src/test/java/org/finos/legend/sdlc/server/inmemory/backend/api/InMemoryProjectApi.java
We are adding the configureProjectInWorkspace as an API to ProjectApi to be able to leverage that in GitlabWorkspaceApi to be able to create project structure when creating a new workspace based out the sandbox setup tag added during project creation
=> Studio Sandbox Setup

pom.xml
Allow dependency on org.slf4j:jul-to-slf4j with test scope throughout legend-sdlc. There are already some modules, such as legend-sdlc-server, which allow it with compile scope.
=> Allow test dependency on org.slf4j:jul-to-slf4j throughout legend-sdlc

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
Switch to use the project tag in the server config. (This would use “legend” in the finos deployment)
=> Use projectTag from config

legend-sdlc-entity-maven-plugin/pom.xml, legend-sdlc-entity-serialization/pom.xml, legend-sdlc-extensions-collection-entity-serializer/pom.xml, legend-sdlc-generation-file-maven-plugin/pom.xml, legend-sdlc-generation-file/pom.xml, legend-sdlc-generation-model-maven-plugin/pom.xml, legend-sdlc-generation-model/pom.xml, legend-sdlc-generation-service-maven-plugin/pom.xml, legend-sdlc-generation-service/pom.xml, legend-sdlc-generation-shared/pom.xml, legend-sdlc-language-pure-compiler/pom.xml, legend-sdlc-model/pom.xml, legend-sdlc-protocol-pure/pom.xml, legend-sdlc-protocol/pom.xml, legend-sdlc-server-fs/pom.xml, legend-sdlc-server-shared/pom.xml, legend-sdlc-server/pom.xml, legend-sdlc-test-generation-maven-plugin/pom.xml, legend-sdlc-test-generation/pom.xml, legend-sdlc-test-reports/pom.xml, legend-sdlc-test-utils/pom.xml, legend-sdlc-version-package-maven-plugin/pom.xml, pom.xml
This reverts commit 27e2eb5ab213e3253676d3766bbd9b17309494ed.
---
I made a mistake during release to put the same version as the latest version 0.171.1
=> Revert "[maven-release-plugin] prepare release legend-sdlc-0.171.1"

legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/auth/GitLabOAuthAuthenticator.java
Newer versions (starting v14) have modified the OAuth authorization page formatting from `h3` to `h1`.
=> Update OAuth flow to accommodate new GitLab behaviour

pom.xml
- Improvement
We are replacing log4j-1.2.17 with reload4j-1.2.19 (This is done remove vulnerabilities). slf4j 1.7.36 version supports reload4j to keep in sync with other legend repo updating version over here as well.
=> updates slf4j version to 1.7.36
